version: "3.8"

services:

  corpdash-auth:
    image: jboss/keycloak:16.1.1
    hostname: corpdash
    container_name: corpdash-auth
    networks:
      - corpdash-net
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: localhost
      DB_PORT: 3306
      DB_SCHEMA: corpdash
      DB_USER: root
      DB_PASSWORD: root
    depends_on:
      - corpdash-db

  corpdash-db:
    image: mysql:8.0.31
    hostname: corpdash
    container_name: corpdash-db
    networks:
      - corpdash-net
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: corpdash
    volumes:
      - db-data:/var/lib/mysql

networks:
  corpdash-net:
    name: corpdash-net

volumes:
  db-data:
    name: db-data

